### ISSUE TITLE
Sequence should include the "to" time

### ISSUE THREAD

**Issue by kenn** [zverok/time_math2#2]
Right now it excludes the time which is set as `to`, but it should be inclusive.

```ruby
> TimeMath.day.sequence(from, to, expand: true)
=> #<TimeMath::Sequence(2016-06-01 00:00:00 -0400 - 2016-06-07 00:00:00 -0400)>

> TimeMath.day.sequence(from, to, expand: true).to_a
=> [2016-06-01 00:00:00 -0400,
 2016-06-02 00:00:00 -0400,
 2016-06-03 00:00:00 -0400,
 2016-06-04 00:00:00 -0400,
 2016-06-05 00:00:00 -0400,
 2016-06-06 00:00:00 -0400]
```

Notice `2016-06-07` is missing in the result.

Right now, a workaround is to add `+1` to `to`, but it's pretty ugly and semantically incorrect.

```ruby
> TimeMath.day.sequence(from, to+1, expand: true).to_a
=> [2016-06-01 00:00:00 -0400,
 2016-06-02 00:00:00 -0400,
 2016-06-03 00:00:00 -0400,
 2016-06-04 00:00:00 -0400,
 2016-06-05 00:00:00 -0400,
 2016-06-06 00:00:00 -0400,
 2016-06-07 00:00:00 -0400]
```

This typically happens when you get a time from a `Date` object with `to_time`. (e.g. GROUP BY aggregations with Rails)

**Comment by zverok** [comment]
Can you show me the use case?
The current solution is pretty opinionated, yet it made from practice. Yet², it was our limited practice, and I'm pretty open to discussions.

Let me explain, how I'm thinking about it:

Sequence is somewhat like range with excluding end (like `(1...5).to_a # => [1,2,3,4]`)

I was initially using it for making charts. Like, "now is Jul 16, 15:00, I want to show client a daily chart for this month, so: 
* the beginning is `TimeMath.month.floor(Time.now) # =>  2016-06-01 00:00:00 +0300`
* the end is `Time.now`
* and what is all data points for my chart? Beginning of each day from start to end (EXCLUDING the end, last point would be `2016-06-16 00:00:00 +0300` in my case)
* the other way to think about this is "ranges for each day" -- and there is `Sequence#ranges` -- and yes, the end of the last range would be `to`.

For me, this way of thinking about things covered all reasonable cases. But, again, I'm pretty open for your use cases and propositions.

**Comment by kenn** [comment]
I'm using it for making charts too.

Here assume that you want to create a chart for daily signups.

```ruby
result = User.group('DATE(created_at)').count
=> {Wed, 01 Jun 2016=>1, Tue, 07 Jun 2016=>3, Thu, 09 Jun 2016=>1}
```

Notice that the keys are `Date`. I want to fill the days in the gap, so I would do something like:

```ruby
from = result.keys.first.to_time
to = result.keys.last.to_time
seq = TimeMath.day.sequence(from, to)
hash_for_chart = seq.to_a.map{|time| [time.to_date, result[time.to_date]] }.to_h
=> {Wed, 01 Jun 2016=>1,
 Thu, 02 Jun 2016=>nil,
 Fri, 03 Jun 2016=>nil,
 Sat, 04 Jun 2016=>nil,
 Sun, 05 Jun 2016=>nil,
 Mon, 06 Jun 2016=>nil,
 Tue, 07 Jun 2016=>3,
 Wed, 08 Jun 2016=>nil}
```

Now, you see `Thu, 09 Jun 2016 => 1` is missing in `hash_for_chart`.

Same applies for weeks, months and other units - the last item will be missing unless it's inclusive.

**Comment by zverok** [comment]
Hm, yes, I see your point. 
Currently, from the top of the head, I can think about two possible solutions:
1) Slightly change sequence API, so you could do: `TimeMath.day.sequence(from...to)` (marking exclusive end) as well as `TimeMath.day.sequence(from..to)` (inclusive end)
2) I wanted to, but haven't done yet a `resample` method. It could be more semantic for your case:
```ruby

result = User.group('DATE(created_at)').count
# => {Wed, 01 Jun 2016=>1, Tue, 07 Jun 2016=>3, Thu, 09 Jun 2016=>1}

# Simpler version:
keys = TimeMath.day.resample(result.keys)
# => [2016-06-01 00:00:00 +0300, 2016-06-02 00:00:00 +0300, 2016-06-03 00:00:00 +0300, 2016-06-04 00:00:00 +0300, 2016-06-05 00:00:00 +0300, 2016-06-06 00:00:00 +0300, 2016-06-07 00:00:00 +0300, 2016-06-08 00:00:00 +0300, 2016-06-09 00:00:00 +0300]
hash_for_chart = keys.map{|time| [time.to_date, result[time.to_date]] }.to_h

# Even better:
TimeMath.day.resample(result) # produces hash you need in one statement
```

WDYT?

BTW, I can see from your case TimeMath should support `Date` natively :) This `to_time`/`to_date` things should just be unneccessary.

**Comment by zverok** [comment]
BTW, just mere inclusion of end doesn't work as expected. Imagine replacing days in your example with weeks:
```ruby
seq = TimeMath.week.sequence(from, to, expand: true)
seq.to_a
# => [#<Date: 2016-05-30 ((2457539j,0s,0n),+0s,2299161j)>, #<Date: 2016-06-06 ((2457546j,0s,0n),+0s,2299161j)>]
```
It is current behavior and EXACTLY what you'd expect (all of your statistics is falling into those two weeks). But with inclusion of sequence end, you'll have, unexpectedly:
```ruby
[*seq.to_a, seq.to]
 => [#<Date: 2016-05-30 ((2457539j,0s,0n),+0s,2299161j)>, #<Date: 2016-06-06 ((2457546j,0s,0n),+0s,2299161j)>, #<Date: 2016-06-13 ((2457553j,0s,0n),+0s,2299161j)>] 
```
The last week is absolutely unrelated to your data (no of your data points falling on it).

All in all, I'm almost finished with resampling feature, will release it today or tomorrow :)

**Comment by zverok** [comment]
Can you please try my develop branch?
```ruby
h = {Date.parse('Wed, 01 Jun 2016')=>1, Date.parse('Tue, 07 Jun 2016')=>3, Date.parse('Thu, 09 Jun 2016')=>1}
# => {#<Date: 2016-06-01 ((2457541j,0s,0n),+0s,2299161j)>=>1, #<Date: 2016-06-07 ((2457547j,0s,0n),+0s,2299161j)>=>3, #<Date: 2016-06-09 ((2457549j,0s,0n),+0s,2299161j)>=>1} 

pp TimeMath.day.resample(h)
# {#<Date: 2016-06-01 ((2457541j,0s,0n),+0s,2299161j)>=>[1],
#  #<Date: 2016-06-02 ((2457542j,0s,0n),+0s,2299161j)>=>[],
#  #<Date: 2016-06-03 ((2457543j,0s,0n),+0s,2299161j)>=>[],
#  #<Date: 2016-06-04 ((2457544j,0s,0n),+0s,2299161j)>=>[],
#  #<Date: 2016-06-05 ((2457545j,0s,0n),+0s,2299161j)>=>[],
#  #<Date: 2016-06-06 ((2457546j,0s,0n),+0s,2299161j)>=>[],
#  #<Date: 2016-06-07 ((2457547j,0s,0n),+0s,2299161j)>=>[3],
#  #<Date: 2016-06-08 ((2457548j,0s,0n),+0s,2299161j)>=>[],
#  #<Date: 2016-06-09 ((2457549j,0s,0n),+0s,2299161j)>=>[1]}

# The default resample just groups all related values in arrays
# You can pass block or symbol, to have the values you need:
pp TimeMath.day.resample(h,&:first)
# {#<Date: 2016-06-01 ((2457541j,0s,0n),+0s,2299161j)>=>1,
#  #<Date: 2016-06-02 ((2457542j,0s,0n),+0s,2299161j)>=>nil,
#  #<Date: 2016-06-03 ((2457543j,0s,0n),+0s,2299161j)>=>nil,
#  #<Date: 2016-06-04 ((2457544j,0s,0n),+0s,2299161j)>=>nil,
#  #<Date: 2016-06-05 ((2457545j,0s,0n),+0s,2299161j)>=>nil,
#  #<Date: 2016-06-06 ((2457546j,0s,0n),+0s,2299161j)>=>nil,
#  #<Date: 2016-06-07 ((2457547j,0s,0n),+0s,2299161j)>=>3,
#  #<Date: 2016-06-08 ((2457548j,0s,0n),+0s,2299161j)>=>nil,
#  #<Date: 2016-06-09 ((2457549j,0s,0n),+0s,2299161j)>=>1}

```

**Comment by zverok** [comment]
(and you can use just `Date` on that branch, without any conversions)

**Comment by kenn** [comment]
`TimeMath.day.sequence(from..to)` looks great.

`resample` sounds good, but just taking `oldest` and `newest` in keys of a given hash may not be enough. I assume most use cases we want the end to be `Time.current` when we draw a chart.

Also keep in mind that keys are not necessarily a `Date`. For instance, if you run a query with Rails + MySQL:

```ruby
# day: User.group('DATE(created_at)')
{ 'Wed, 01 Jun 2016' => 1 }
# hour: User.group(['DATE(created_at)', 'HOUR(created_at)'])
{ ['Wed, 01 Jun 2016', 14] => 1 }
# week: User.group('YEARWEEK(created_at, 3)') # option 3 to keep parity with ruby's cweek
{ 201622 => 1 }
# month: User.group(['YEAR(created_at)', 'MONTH(created_at)'])
{ [2016, 6] => 1 }
```

As you can see, many types of keys are possible. So I'm not sure if just supporting `Date` is enough for abstraction. I would stick with `Time` as a universal internal state. (and `floor` to a zero-filled `Time` when coarse units are requested)

> It is current behavior and EXACTLY what you'd expect (all of your statistics is falling into those two weeks). But with inclusion of sequence end, you'll have, unexpectedly:

I'm not sure what you mean, but as long as the result of `to_a` ends with `to` (this is my definition of inclusion), it is good.

On a side note, I don't get what `expand` means, either. I thought it would "roundup" the end, as in `2016-06-09 14:00:00` becomes `2016-06-10 00:00:00`, then finally "exclusive" range makes sense - we could use it like so:

```ruby
from = 2016-06-01 00:00:00
to   = 2016-06-10 00:00:00
User.where('created_at >= ? AND created_at < ?', from, to)
```

It would be useful to build a query. Right now I have no idea what it is intended for?

**Comment by zverok** [comment]
I'll try to think of everything you write in the next days. It is very helpful and very real, so, I'll try my best to understand the best AND minimal concepts to handle the important cases.

Could you please try (currently implemented) `resample` and say what you think?..

And your note about resampling to current time makes me think, thanks.

**Comment by zverok** [comment]
(And I'll greatly appreciate more examples of real-life cases you want to use `time_math` at)

**Comment by zverok** [comment]
> Also keep in mind that keys are not necessarily a `Date`. 

Yeah, I'm aware of it. But the time_math's scope is to do time math in minimal number of concepts, but in a covenient way, not the "be able to draw chart from any data ActiveRecord could return" :) 

In some of your cases it is obvious that result could be converted in Time/Date:
```ruby
User.group(['YEAR(created_at)', 'MONTH(created_at)']).count
=> { [2016, 6] => 1 }
 { [2016, 6] => 1 }.map { |k,v| [Date.new(*k),v] }.to_h
 => {#<Date: 2016-06-01 ((2457541j,0s,0n),+0s,2299161j)>=>1}
```
...but as of others—I'm not sure. I even can't imagine what kind of chart/math is reasonable/expected with results of `User.group(['DATE(created_at)', 'HOUR(created_at)']).count`. Can you please explain?..

> On a side note, I don't get what `expand` means, either. I thought it would "roundup" the end, as in `2016-06-09 14:00:00` becomes `2016-06-10 00:00:00`, 

It does exactly this:
```ruby
seq = TimeMath.day.sequence(Time.parse('2016-06-06 13:00'), Time.parse('2016-06-09 14:00'))
# => #<TimeMath::Sequence(2016-06-06 13:00:00 +0300 - 2016-06-09 14:00:00 +0300)>
eseq = seq.expand
# => #<TimeMath::Sequence(2016-06-06 00:00:00 +0300 - 2016-06-10 00:00:00 +0300)> 
seq.to_a
# => [2016-06-06 13:00:00 +0300, 2016-06-07 13:00:00 +0300, 2016-06-08 13:00:00 +0300, 2016-06-09 13:00:00 +0300]
eseq.to_a
#  => [2016-06-06 00:00:00 +0300, 2016-06-07 00:00:00 +0300, 2016-06-08 00:00:00 +0300, 2016-06-09 00:00:00 +0300]
seq.ranges
#  => [2016-06-06 13:00:00 +0300...2016-06-07 13:00:00 +0300, 2016-06-07 13:00:00 +0300...2016-06-08 13:00:00 +0300, 2016-06-08 13:00:00 +0300...2016-06-09 13:00:00 +0300, 2016-06-09 13:00:00 +0300...2016-06-09 14:00:00 +0300]
eseq.ranges
#  => [2016-06-06 00:00:00 +0300...2016-06-07 00:00:00 +0300, 2016-06-07 00:00:00 +0300...2016-06-08 00:00:00 +0300, 2016-06-08 00:00:00 +0300...2016-06-09 00:00:00 +0300, 2016-06-09 00:00:00 +0300...2016-06-10 00:00:00 +0300]
```

To be honest, I'd be happy to work on complicated problems case-by-case. I'm not 100% sure the current design is best possible, yet I feel like it providing simple and useful mental model, which just should be grasped for easy usage. For example, I'm still not convinced there is any real case for `to` inclusion in `Sequence#to_a`.

**Comment by kenn** [comment]
> Yeah, I'm aware of it. But the time_math's scope is to do time math in minimal number of concepts, but in a covenient way, not the "be able to draw chart from any data ActiveRecord could return" :)

Yep, I agree. My point was that `resample` may be a premature abstraction otherwise. `sequence` makes perfect sense for a small library like TimeMath, and I'm using it by passing `Date.new(2016,6,9).to_time + 1` as a `to` parameter, however it is kludgy.

> ...but as of others—I'm not sure. I even can't imagine what kind of chart/math is reasonable/expected with results of User.group(['DATE(created_at)', 'HOUR(created_at)']).count. Can you please explain?..

Any units, down to minute and second, can be a unit of grouping - take a look at [this popular library](https://github.com/ankane/groupdate/blob/master/lib/groupdate/magic.rb#L30-L80). Some of my projects have "group by seconds" query on a table with many INSERTs per second.

Here's an example of NewRelic, which groups transactions by "minutes" and displays a scaled chart.

<img width="899" alt="screen shot 2016-06-18 at 12 24 37 pm" src="https://cloud.githubusercontent.com/assets/10350/16172303/dac10cd2-3553-11e6-8806-604d185668fb.png">

> On a side note, I don't get what expand means, either. I thought it would "roundup" the end, as in 2016-06-09 14:00:00 becomes 2016-06-10 00:00:00,
> It does exactly this:
> seq = TimeMath.day.sequence(Time.parse('2016-06-06 13:00'), Time.parse('2016-06-09 14:00'))

Your example has non-zero hour. When we get a time value from a date and `to_time`, we always get `00:00:00`. Then again the result is:

```ruby
seq = TimeMath.day.sequence(Time.parse('2016-06-06 00:00'), Time.parse('2016-06-09 00:00'))
eseq = seq.expand
seq.to_a
 => [2016-06-06 00:00:00 -0400, 2016-06-07 00:00:00 -0400, 2016-06-08 00:00:00 -0400]
eseq.to_a
 => [2016-06-06 00:00:00 -0400, 2016-06-07 00:00:00 -0400, 2016-06-08 00:00:00 -0400]
seq.ranges
 => [2016-06-06 00:00:00 -0400...2016-06-07 00:00:00 -0400, 2016-06-07 00:00:00 -0400...2016-06-08 00:00:00 -0400, 2016-06-08 00:00:00 -0400...2016-06-09 00:00:00 -0400]
eseq.ranges
 => [2016-06-06 00:00:00 -0400...2016-06-07 00:00:00 -0400, 2016-06-07 00:00:00 -0400...2016-06-08 00:00:00 -0400, 2016-06-08 00:00:00 -0400...2016-06-09 00:00:00 -0400]
```

`2016-06-09` is missing with or without `expand`, so it is either 

- inclusive `to`, or
- `expand` to advance even with zero values

Otherwise it's a dead end.

I hope you see my point?

> To be honest, I'd be happy to work on complicated problems case-by-case. I'm not 100% sure the current design is best possible, yet I feel like it providing simple and useful mental model, which just should be grasped for easy usage. For example, I'm still not convinced there is any real case for to inclusion in Sequence#to_a.

If you think passing a time created by `Date#to_time` is a "complicated" use case, I have to say I'm surprised. 😎 To me personally, exclusive range / sequence has no use case, and very counterintuitive.

But if you don't agree that's fine, I'll continue to use `to_time + 1` and call it done. Thanks for the nice library! 😆

**Comment by zverok** [comment]
OK, I think I'll add creating sequences by ranges in the next version (due on the upcoming week) and we'll see how it will play. To be honest, I'm still not 100% sure I've got your point, but creating sequences from ranges seem pretty useful in any case.

**Comment by zverok** [comment]
Aaaaand... Here we go! https://github.com/zverok/time_math2/blob/master/CHANGELOG.md#005-2016-06-25

Both new sequence creation syntax (**instead** of old) and resampling was added to this release.
Have fun!

**Comment by kenn** [comment]
Great, thanks @zverok ! 👍
