### ISSUE TITLE
Use different timezone from system timezone

### ISSUE THREAD

**Issue by wojtha** [zverok/time_math2#4]
### Use case

In our system we work with data in UTC timezone. So the use case is that we get some time interval (from, to) and we need to generate sequence of days, hours and so on inside this interval.

E.g.

```
2016-01-01 00:00:00 UTC
2016-01-02 00:00:00 UTC
2016-01-03 00:00:00 UTC
```

However our system time zone is different.

### Synopsis

TimeMath is pinned to `ENV['TZ']` so the only way how to work in different TZ without unreliable offset calculations are:

A) setting `ENV['TZ']` globally for whole application

```ruby
# config/timezone.rb
ENV['TZ'] = 'UTC'
```

B) overriding `ENV['TZ']` temporarily

```ruby
# Switches temporarily the ENV['TZ'] to different timezone
# @see http://stackoverflow.com/a/15669411
def with_time_zone(tz_name)
  prev_tz = ENV['TZ']
  ENV['TZ'] = tz_name
  yield
ensure
  ENV['TZ'] = prev_tz
end
```

So we can use it in code like this:

```ruby
with_time_zone('UTC') do
  from = TimeMath.day.floor(Time.at(from.to_i)).utc
  to   = TimeMath.day.ceil(Time.at(to.to_i)).utc

  TimeMath.day.sequence(from...to).each do |date|
    puts date
  end
end
```

Without wrapping the code to the `with_time_zone('UTC')` the resulting dates of the methods `TimeMath.day.ceil` or `TimeMath.day.floor` are converted in the context of the system `ENV['TZ']`. So for instance instead of `2016-01-01 00:00:00 UTC` we get `2015-12-31 22:00:00 UTC` if we are in `ENV['TZ'] = "CET"`.

Is there better way how to do it?

It would be really nice to have some support for changing the context of time zone without overriding the global `ENV['TZ']` variable, something similar to `Time.zone` or `Time#in_timezone` from `ActiveSupport`

**Comment by zverok** [comment]
Well, you'll laugh... I've had a (false) believing that `Time.mktime` has a timezone name as a last argument, and relied on it. Now I've fixed everything to just use `gmt_offset` and released new version. It is worse than planned (automatic handling of DST is missing now... OK, it was also missed previously, but I believed it is there), so, I am not quite sure it is the best solution possible. Please try 0.0.6 and tell me what you think.

To be honest, as far as I can understand, good timezones handling in relation to DST requires full tzinfo database support :( While TimeMath was planned to be simple.

Also, I was quite fascinated that I hadn't add `each` to `Sequence` previously, thanks for pointing at it.
