### ISSUE TITLE
Bug with month#advance

### ISSUE THREAD

**Issue by dikond** [zverok/time_math2#5]
Hello!
I've encountered a really unexpected bug with following parameters:
```ruby
TimeMath.month.advance(DateTime.new(2017, 5, 29), 9)
```

It seems this is happening because of `29` number of a day. It tries to create such a date at some point:
```ruby
DateTime.new(2018, 2, 29, 11, 47, 58)
# => ArgumentError: invalid date
```

Ruby's `#next_month` is doing fine here:
```ruby
DateTime.new(2017, 5, 29).next_month(9)
# => #<DateTime: 2018-02-28T00:00:00+00:00 ((2458178j,0s,0n),+0s,2299161j)>
```

But we'd prefer to use a consistent approach to time manipulation. If you'd need any help, please let me know!

**Comment by zverok** [comment]
Confirmed. 
In initial implementation I've relied on `Time` smartness: 
```ruby
Time.new(2017,2,29)
# => 2017-03-01 00:00:00 +0200 
```
It is not this way for `DateTime`:
```ruby
DateTime.new(2017,2,29)
# ArgumentError: invalid date
```

Fighting it currently.

**Comment by zverok** [comment]
Should work in `master`, please confirm.

**Comment by dikond** [comment]
@zverok just tested it with master - it does work. I believe we can close it with a new gem version, right?

**Comment by zverok** [comment]
Yep, will do the release in evening. Thanks for pointing out to the problem! Investigating it in fact led to cleaner and better designed code.

**Comment by dikond** [comment]
Glad my feedback was helpful! And thanks for a quick response :)

**Comment by zverok** [comment]
0.0.7 released!
